scrape_configs:
- job_name: 'otel-collector'
  scrape_interval: 1s
  static_configs:
  - targets: ['otel-collector:8889']
  - targets: ['otel-collector:8888']
- job_name: 'otel-collector-aaS'
  scrape_interval: 1s
  static_configs:
  - targets: [host.docker.internal:8889]
